version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    restart: always
    ports:
      - 50070:50070
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ~/data:/data
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode1
    restart: always
    hostname:
      datanode1
    ports:
      - 50075:50075
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    env_file:
      - ./hadoop-hive.env

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode2
    restart: always
    hostname:
      datanode2
    ports:
      - 50076:50075
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    env_file:
      - ./hadoop-hive.env

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop2.7.4-java8
    container_name: resourcemanager
    restart: always
    hostname:
      resourcemanager
    ports:
      - 8088:8088
      - 8032:8032
      - 8031:8031
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode1:50075 datanode2:50075"
    env_file:
      - ./hadoop-hive.env

  nodemanager1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop2.7.4-java8
    container_name: nodemanager1
    hostname:
      nodemanager1
    restart: always
    ports:
      - 8042:8042
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode1:50075 datanode2:50075 resourcemanager:8088"
    env_file:
      - ./hadoop-hive.env

  nodemanager2:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop2.7.4-java8
    container_name: nodemanager2
    hostname:
      nodemanager2
    restart: always
    ports:
      - 8043:8042
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode1:50075 datanode2:50075 resourcemanager:8088"
    env_file:
      - ./hadoop-hive.env


  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop2.7.4-java8
    container_name: historyserver
    restart: always
    ports:
      - 8188:8188
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode1:50075 datanode2:50075 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop-hive.env

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    hostname: mongo
    volumes:
      - mongoDB:/data/db
      - ./data:/project/data/

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    hostname: mongo-express
    container_name: mongo-express
    environment:
      SERVICE_PRECONDITION: "mongo"
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_historyserver:
  mongoDB:
